/* Generated By:JavaCC: Do not edit this line. MappingFileParserConstants.java */
package de.ust.skill.manipulator.specificationMapping.mappingfileParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MappingFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SKILLNAME = 5;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SKILLNAME>",
    "<UNICODE_LETTER>",
    "\"->\"",
    "\"{\"",
    "\"}\"",
  };

}
